import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import { registerSW } from 'virtual:pwa-register';

const rootElement = document.getElementById('root');
if (!rootElement) {
  throw new Error("Could not find root element to mount to");
}

const root = ReactDOM.createRoot(rootElement);
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);

// Register Service Worker (generated by vite-plugin-pwa)
registerSW({
  immediate: true,
  onNeedRefresh() {
    // Minimal UX: ask user; you can replace with a nicer in-app toast later.
    if (confirm('发现新版本，是否立即更新？')) {
      window.location.reload();
    }
  },
  onOfflineReady() {
    // eslint-disable-next-line no-console
    console.log('App is ready to work offline');
  },
});
